"on":
- pull_request
name: Porter Preview Environment
jobs:
  porter-preview:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.4
    - name: Create Porter preview env
      timeout-minutes: 30
      uses: porter-dev/porter-preview-action@v0.1.0
      with:
        action_id: ${{ github.run_id }}
        branch: ${{ github.head_ref }}
        cluster: "34"
        host: https://dashboard.dev.getporter.dev
        installation_id: "18424822"
        namespace: pr-${{ github.event.pull_request.number }}-node
        pr_id: ${{ github.event.pull_request.number }}
        pr_name: ${{ github.event.pull_request.title }}
        project: "3"
        repo_name: node
        repo_owner: ${{ github.repository_owner }}
        token: ${{ secrets.PORTER_TOKEN_3 }}
